<a href="https://colab.research.google.com/github/philxhuang/udacity-projects/blob/master/starter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Starter: Basic Data Manipulation

All the source codes are provided by Udacity. The codes are also modified by me to facilitate learning so the codes below should be easier to understand than random OOP attributes.

In [0]:
import torch
import torchvision

In [0]:
# use this to check your PyTorch version and GUP availability
print(torch.__version__)
print(torch.cuda.is_available())

1.1.0
True


In [0]:
def activation(x):
    """ Sigmoid activation function 
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [0]:
### Generate some data
torch.manual_seed(10) # Set the random seed so things are predictable

# setting a seed has to do with how python generates pseudo "random" data, read more on your own

# Features are 5 random normal variables
features = torch.randn((1, 5)) # create [1,5] matrix/row vector
print(features)
# True weights for our data, random normal variables again
weights = torch.randn_like(features) # create a matrix with the same (dimension)
print(weights)
# and a true bias term
bias = torch.randn((1, 1)) # this is a [1,1] dot vector as bias
print(bias)

tensor([[-0.6014, -1.0122, -0.3023, -1.2277,  0.9198]])
tensor([[-0.3485, -0.8692, -0.9582, -1.1920,  1.9050]])
tensor([[-0.9373]])


In [0]:
# Now, make our labels from our data and true weights
'''
y = activation(torch.sum(features * weights) + bias)
y = activation((features * weights).sum() + bias)
'''
# this is the most basic way to do it, but we can write cleaner code

'\ny = activation(torch.sum(features * weights) + bias)\ny = activation((features * weights).sum() + bias)\n'

In [0]:
# This is much cleane
'''
torch.mm() does not broadcast, only for 2-d
torch.matmal() does broad cast, for higher demensions
'''

#                         [1,5]    *    [5,1]          [1]
y = activation(torch.mm(features, weights.view(5,1)) + bias)
print("one forward pass creates the inner/dot product at", y)

one forward pass creates the inner/dot product at tensor([[0.9748]])


What we just did is to create a super simple neural network with one weight matrix (1 layer) and pass all the weights for only once.

Now let's create a network with 2 layers. Notice that layers will decrease over time because in **THIS PARTICULAR EXERCISE**, we want our input matrices to come out as an inner product.

In [0]:
### Generate some data
torch.manual_seed(10) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3)) # dimension [1,3]
print('features: ', features)

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer, [3,2]
W1 = torch.randn(n_input, n_hidden)
print('W1: ', W1)
# Weights for hidden layer to output layer, [2,1]
W2 = torch.randn(n_hidden, n_output)
print('W2:', W2)

# and bias terms for hidden and output layers, [1,# of columns]
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))
print(B1, B2)

features:  tensor([[-0.6014, -1.0122, -0.3023]])
W1:  tensor([[-1.2277,  0.9198],
        [-0.3485, -0.8692],
        [-0.9582, -1.1920]])
W2: tensor([[ 1.9050],
        [-0.9373]])
tensor([[-0.8465,  2.2678]]) tensor([[1.3615]])


In [0]:
# Now pass through the matrix in order
h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
print(output)

tensor([[0.8418]])


# Bonus: Numpy-Torch Conversion

In [0]:
import numpy as np
a = np.random.rand(4,3)
print('a is a numpy array', a)

a is a numpy array [[0.66043138 0.49387078 0.50198118]
 [0.14943039 0.66726578 0.46902102]
 [0.36100858 0.4058508  0.08473571]
 [0.14358369 0.77798556 0.06239596]]


In [0]:
b = torch.from_numpy(a)
print('b is a torch tensor object converted from numpy array', b)

b is a torch tensor object converted from numpy array tensor([[0.6604, 0.4939, 0.5020],
        [0.1494, 0.6673, 0.4690],
        [0.3610, 0.4059, 0.0847],
        [0.1436, 0.7780, 0.0624]], dtype=torch.float64)


In [0]:
c = b.numpy()
print('c is a new variable, converted back to numpy array', c)

c is a new variable, converted back to numpy array [[0.66043138 0.49387078 0.50198118]
 [0.14943039 0.66726578 0.46902102]
 [0.36100858 0.4058508  0.08473571]
 [0.14358369 0.77798556 0.06239596]]


In [0]:
# Multiply PyTorch Tensor by 2, in place
b.mul_(2)
# Please know that this method is pretty old-fashioned.
# For more, please go learn BROADCASTING.

tensor([[1.3209, 0.9877, 1.0040],
        [0.2989, 1.3345, 0.9380],
        [0.7220, 0.8117, 0.1695],
        [0.2872, 1.5560, 0.1248]], dtype=torch.float64)

In [0]:
print(a)
print(b, 'is the same as an alised a array')
print(c)
'''
Unfortunately, the method torch.from_numpy shares the same memory.
The best approch is use something like tensor(), not Tensor()
Please do understand these subtle differences. Check out the documentation.
'''

[[1.32086275 0.98774156 1.00396236]
 [0.29886079 1.33453156 0.93804204]
 [0.72201715 0.81170161 0.16947142]
 [0.28716737 1.55597111 0.12479191]]
tensor([[1.3209, 0.9877, 1.0040],
        [0.2989, 1.3345, 0.9380],
        [0.7220, 0.8117, 0.1695],
        [0.2872, 1.5560, 0.1248]], dtype=torch.float64) is the same as an alised a array
[[1.32086275 0.98774156 1.00396236]
 [0.29886079 1.33453156 0.93804204]
 [0.72201715 0.81170161 0.16947142]
 [0.28716737 1.55597111 0.12479191]]


'\nUnfortunately, the method torch.from_numpy shares the same memory.\nThe best approch is use something like tensor(), not Tensor()\nPlease do understand these subtle differences. Check out the documentation.\n'

End of Lession